import bcrypt from 'bcryptjs';
import { db } from '../config/db.ts';
import { DatabaseState } from './schema.ts';

export async function seedDatabase(forceReset = false): Promise<void> {
  const currentState = db.getState();
  if (!forceReset && currentState.users.length > 0 && currentState.santri.length > 0) {
    return;
  }

  const adminHash = await bcrypt.hash('admin123', 10);
  const pembinaHash = await bcrypt.hash('pembina123', 10);
  const bendaharaHash = await bcrypt.hash('bendahara123', 10);

  const now = new Date().toISOString();

  const seededState: DatabaseState = {
    users: [
      {
        id: 1,
        username: 'admin',
        password_hash: adminHash,
        full_name: 'Ustadz Ahmad Fauzi, S.Pd.I',
        role: 'admin',
        building_assignment: 'Semua',
        phone_number: '081234567800',
        is_active: true,
        created_at: '2026-01-10T08:00:00.000Z',
        updated_at: now,
      },
      {
        id: 2,
        username: 'pembina',
        password_hash: pembinaHash,
        full_name: 'Ustadz Hendra Kusuma, Lc.',
        role: 'pembina',
        building_assignment: 'Gedung A',
        phone_number: '081298765432',
        is_active: true,
        created_at: '2026-01-12T08:30:00.000Z',
        updated_at: now,
      },
      {
        id: 3,
        username: 'pembina_b',
        password_hash: pembinaHash,
        full_name: 'Ustadzah Siti Aminah, M.Pd.',
        role: 'pembina',
        building_assignment: 'Gedung B',
        phone_number: '081345678901',
        is_active: true,
        created_at: '2026-01-15T09:00:00.000Z',
        updated_at: now,
      },
      {
        id: 4,
        username: 'bendahara',
        password_hash: bendaharaHash,
        full_name: 'H. Ridwan Kamil, S.E.',
        role: 'bendahara',
        building_assignment: 'Semua',
        phone_number: '081122334455',
        is_active: true,
        created_at: '2026-01-18T10:00:00.000Z',
        updated_at: now,
      },
    ],
    santri: [
      {
        id: 1,
        nis: '202401001',
        full_name: 'Ahmad Raihan',
        gender: 'L',
        birth_place: 'Bandung',
        birth_date: '2009-04-12',
        room_number: 'A-101',
        building: 'Gedung A',
        class_grade: '10 IPA 1',
        parent_name: 'H. Abdullah',
        parent_phone: '081234567890',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-20T08:00:00.000Z',
      },
      {
        id: 2,
        nis: '202401002',
        full_name: 'Siti Sarah',
        gender: 'P',
        birth_place: 'Surabaya',
        birth_date: '2008-08-23',
        room_number: 'B-204',
        building: 'Gedung B',
        class_grade: '11 IPS 2',
        parent_name: 'Drs. H. Mulyadi',
        parent_phone: '082345678901',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-20T08:15:00.000Z',
      },
      {
        id: 3,
        nis: '202401003',
        full_name: 'Muhammad Bilal',
        gender: 'L',
        birth_place: 'Yogyakarta',
        birth_date: '2009-11-05',
        room_number: 'A-102',
        building: 'Gedung A',
        class_grade: '10 IPA 2',
        parent_name: 'Umar Faruq',
        parent_phone: '083456789012',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-21T09:00:00.000Z',
      },
      {
        id: 4,
        nis: '202401004',
        full_name: 'Fatimah Az-Zahra',
        gender: 'P',
        birth_place: 'Malang',
        birth_date: '2007-02-19',
        room_number: 'B-201',
        building: 'Gedung B',
        class_grade: '12 IPA 1',
        parent_name: 'Dr. Usman',
        parent_phone: '084567890123',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-22T09:30:00.000Z',
      },
      {
        id: 5,
        nis: '202401005',
        full_name: 'Yusuf Habibi',
        gender: 'L',
        birth_place: 'Solo',
        birth_date: '2008-06-30',
        room_number: 'A-103',
        building: 'Gedung A',
        class_grade: '11 IPA 1',
        parent_name: 'Ibrahim Habib',
        parent_phone: '085678901234',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-23T10:00:00.000Z',
      },
      {
        id: 6,
        nis: '202401006',
        full_name: 'Aisyah Humaira',
        gender: 'P',
        birth_place: 'Semarang',
        birth_date: '2009-01-14',
        room_number: 'B-202',
        building: 'Gedung B',
        class_grade: '10 IPS 1',
        parent_name: 'H. Hasan Basri',
        parent_phone: '081390876543',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-24T10:15:00.000Z',
      },
      {
        id: 7,
        nis: '202401007',
        full_name: 'Zaidan Al-Farizi',
        gender: 'L',
        birth_place: 'Bogor',
        birth_date: '2007-09-10',
        room_number: 'A-101',
        building: 'Gedung A',
        class_grade: '12 IPS 1',
        parent_name: 'H. Lukman Hakim',
        parent_phone: '081288776655',
        photo_url: '',
        status: 'aktif',
        created_at: '2026-01-25T11:00:00.000Z',
      },
      {
        id: 8,
        nis: '202301019',
        full_name: 'Rizky Ramadhan',
        gender: 'L',
        birth_place: 'Jakarta',
        birth_date: '2006-05-21',
        room_number: 'A-104',
        building: 'Gedung A',
        class_grade: 'Alumni 2025',
        parent_name: 'Ir. Bambang Sudibyo',
        parent_phone: '081199887766',
        photo_url: '',
        status: 'alumni',
        created_at: '2025-07-01T08:00:00.000Z',
      },
    ],
    violations: [
      {
        id: 1,
        santri_id: 2,
        violation_date: '2026-09-12',
        violation_type: 'Terlambat Apel Pagi Asrama',
        points: 5,
        penalty: 'Membaca Al-Mulk & piket halaman',
        recorded_by: 'Ustadzah Siti Aminah, M.Pd.',
        created_at: '2026-09-12T07:00:00.000Z',
      },
      {
        id: 2,
        santri_id: 3,
        violation_date: '2026-09-18',
        violation_type: 'Keluar area asrama tanpa surat izin',
        points: 20,
        penalty: 'Teguran lisan, pemanggilan pembina & piket masjid 3 hari',
        recorded_by: 'Ustadz Hendra Kusuma, Lc.',
        created_at: '2026-09-18T16:30:00.000Z',
      },
      {
        id: 3,
        santri_id: 5,
        violation_date: '2026-10-02',
        violation_type: 'Tidak mengikuti jamaah Subuh tepat waktu',
        points: 10,
        penalty: 'Hafalan 15 kosakata Bahasa Arab & istighfar 100x',
        recorded_by: 'Ustadz Hendra Kusuma, Lc.',
        created_at: '2026-10-02T05:30:00.000Z',
      },
      {
        id: 4,
        santri_id: 7,
        violation_date: '2026-10-04',
        violation_type: 'Membawa perangkat elektronik tanpa izin (HP)',
        points: 35,
        penalty: 'Surat Peringatan 1 (SP1), penyitaan HP 1 semester & pemanggilan wali',
        recorded_by: 'Ustadz Ahmad Fauzi, S.Pd.I',
        created_at: '2026-10-04T21:15:00.000Z',
      },
    ],
    counseling: [
      {
        id: 1,
        santri_id: 3,
        counseling_date: '2026-09-19',
        topic: 'Evaluasi kedisiplinan keluar asrama & adaptasi jadwal belajar',
        follow_up: 'Monitoring kehadiran jam malam oleh musyrif kamar A-102 selama 2 pekan',
        counselor_name: 'Ustadz Hendra Kusuma, Lc.',
        created_at: '2026-09-19T10:00:00.000Z',
      },
      {
        id: 2,
        santri_id: 4,
        counseling_date: '2026-09-25',
        topic: 'Konsultasi pemilihan jurusan perguruan tinggi & beasiswa Timur Tengah',
        follow_up: 'Pendampingan pemberkasan seleksi Universitas Al-Azhar & PTN',
        counselor_name: 'Ustadzah Siti Aminah, M.Pd.',
        created_at: '2026-09-25T14:00:00.000Z',
      },
      {
        id: 3,
        santri_id: 7,
        counseling_date: '2026-10-05',
        topic: 'Pembinaan khusus pasca SP1 penggunaan gawai di asrama',
        follow_up: 'Komunikasi berkala dengan orang tua (H. Lukman Hakim) & evaluasi bulanan',
        counselor_name: 'Ustadz Ahmad Fauzi, S.Pd.I',
        created_at: '2026-10-05T09:30:00.000Z',
      },
    ],
    achievements: [
      {
        id: 1,
        santri_id: 4,
        achievement_date: '2026-08-17',
        title: 'Juara 1 Musabaqah Hifdzil Quran (MHQ) 10 Juz Tingkat Provinsi',
        level: 'Provinsi',
        reward: 'Sertifikat Penghargaan & Beasiswa SPP 3 Bulan',
        points: 20,
        created_at: '2026-08-17T15:00:00.000Z',
      },
      {
        id: 2,
        santri_id: 1,
        achievement_date: '2026-09-10',
        title: 'Syahadah Tasmi Hafalan 5 Juz Sekali Duduk',
        level: 'Internal Pesantren',
        reward: 'Piagam Tahfidz & Voucher Koperasi Santri',
        points: 10,
        created_at: '2026-09-10T11:00:00.000Z',
      },
      {
        id: 3,
        santri_id: 6,
        achievement_date: '2026-10-01',
        title: 'Juara 2 Olimpiade Sains Nasional (OSN) Matematika Kabupaten',
        level: 'Kabupaten/Kota',
        reward: 'Medali Perak & Uang Pembinaan',
        points: 15,
        created_at: '2026-10-01T13:30:00.000Z',
      },
    ],
    financial_spp: [
      {
        id: 1,
        santri_id: 1,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'lunas',
        paid_at: '2026-10-02T09:15:00.000Z',
        updated_at: '2026-10-02T09:15:00.000Z',
      },
      {
        id: 2,
        santri_id: 2,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'lunas',
        paid_at: '2026-10-03T10:40:00.000Z',
        updated_at: '2026-10-03T10:40:00.000Z',
      },
      {
        id: 3,
        santri_id: 3,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'tunggakan',
        paid_at: null,
        updated_at: '2026-10-01T08:00:00.000Z',
      },
      {
        id: 4,
        santri_id: 4,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'lunas',
        paid_at: '2026-10-01T14:20:00.000Z',
        updated_at: '2026-10-01T14:20:00.000Z',
      },
      {
        id: 5,
        santri_id: 5,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'tunggakan',
        paid_at: null,
        updated_at: '2026-10-01T08:00:00.000Z',
      },
      {
        id: 6,
        santri_id: 6,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'lunas',
        paid_at: '2026-10-04T11:05:00.000Z',
        updated_at: '2026-10-04T11:05:00.000Z',
      },
      {
        id: 7,
        santri_id: 7,
        month: 'Oktober',
        year: 2026,
        amount: 850000,
        status: 'tunggakan',
        paid_at: null,
        updated_at: '2026-10-01T08:00:00.000Z',
      },
    ],
    pocket_money: [
      {
        id: 1,
        santri_id: 1,
        transaction_type: 'masuk',
        amount: 500000,
        description: 'Setoran uang saku bulanan dari orang tua (H. Abdullah)',
        transaction_date: '2026-10-01',
      },
      {
        id: 2,
        santri_id: 1,
        transaction_type: 'keluar',
        amount: 125000,
        description: 'Penarikan uang saku mingguan & pembelian kitab kuning',
        transaction_date: '2026-10-04',
      },
      {
        id: 3,
        santri_id: 2,
        transaction_type: 'masuk',
        amount: 600000,
        description: 'Transfer tabungan santri bulan Oktober',
        transaction_date: '2026-10-02',
      },
      {
        id: 4,
        santri_id: 2,
        transaction_type: 'keluar',
        amount: 150000,
        description: 'Kebutuhan koperasi & perlengkapan mandi',
        transaction_date: '2026-10-05',
      },
      {
        id: 5,
        santri_id: 4,
        transaction_type: 'masuk',
        amount: 750000,
        description: 'Setoran tabungan & apresiasi lomba MHQ',
        transaction_date: '2026-10-01',
      },
    ],
    operational_cash: [
      {
        id: 1,
        type: 'masuk',
        category: 'Penerimaan SPP',
        amount: 18500000,
        description: 'Rekapitulasi dana SPP santri tahap awal Oktober 2026',
        transaction_date: '2026-10-02',
        recorded_by: 'H. Ridwan Kamil, S.E.',
      },
      {
        id: 2,
        type: 'masuk',
        category: 'Donasi / Wakaf',
        amount: 5000000,
        description: 'Infaq komite wali santri untuk perpustakaan asrama',
        transaction_date: '2026-10-03',
        recorded_by: 'H. Ridwan Kamil, S.E.',
      },
      {
        id: 3,
        type: 'keluar',
        category: 'Konsumsi & Dapur',
        amount: 6200000,
        description: 'Belanja bahan pokok katering asrama pekan ke-1 Oktober',
        transaction_date: '2026-10-03',
        recorded_by: 'H. Ridwan Kamil, S.E.',
      },
      {
        id: 4,
        type: 'keluar',
        category: 'Utilitas & Kebersihan',
        amount: 2450000,
        description: 'Tagihan listrik PLN, PDAM, dan internet asrama Gedung A & B',
        transaction_date: '2026-10-05',
        recorded_by: 'H. Ridwan Kamil, S.E.',
      },
      {
        id: 5,
        type: 'keluar',
        category: 'Pemeliharaan Gedung',
        amount: 1350000,
        description: 'Perbaikan instalasi lampu & keran wudhu Gedung A',
        transaction_date: '2026-10-06',
        recorded_by: 'H. Ridwan Kamil, S.E.',
      },
    ],
    permissions: [
      {
        id: 1,
        santri_id: 1,
        start_date: '2026-10-08',
        end_date: '2026-10-10',
        reason: 'Menghadiri pernikahan kakak kandung di Bandung',
        status: 'disetujui',
        approved_by: 'Ustadz Hendra Kusuma, Lc.',
        created_at: '2026-10-06T08:30:00.000Z',
      },
      {
        id: 2,
        santri_id: 2,
        start_date: '2026-10-09',
        end_date: '2026-10-09',
        reason: 'Kontrol kesehatan gigi rutin di RS Islam',
        status: 'disetujui',
        approved_by: 'Ustadzah Siti Aminah, M.Pd.',
        created_at: '2026-10-06T10:15:00.000Z',
      },
      {
        id: 3,
        santri_id: 5,
        start_date: '2026-10-11',
        end_date: '2026-10-13',
        reason: 'Izin pulang menjenguk nenek sakit di Solo',
        status: 'diproses',
        approved_by: '-',
        created_at: '2026-10-07T07:45:00.000Z',
      },
    ],
    activity_logs: [
      {
        id: 1,
        user_id: 1,
        user_name: 'Ustadz Ahmad Fauzi, S.Pd.I',
        action: 'Inisialisasi Sistem',
        details: 'Database awal SIM-ASRAMA berhasil dimuat beserta akun Admin, Pembina, dan Bendahara.',
        timestamp: '2026-10-01T08:00:00.000Z',
      },
      {
        id: 2,
        user_id: 4,
        user_name: 'H. Ridwan Kamil, S.E.',
        action: 'Verifikasi SPP',
        details: 'Mencatat pelunasan SPP bulan Oktober 2026 untuk 4 santri aktif.',
        timestamp: '2026-10-04T11:10:00.000Z',
      },
      {
        id: 3,
        user_id: 1,
        user_name: 'Ustadz Ahmad Fauzi, S.Pd.I',
        action: 'Pencatatan Pelanggaran & Konseling',
        details: 'Mencatat pelanggaran SP1 atas nama Zaidan Al-Farizi beserta jadwal bimbingan.',
        timestamp: '2026-10-05T09:35:00.000Z',
      },
    ],
  };

  db.setState(seededState);
}
